#!/usr/bin/env python3
from pathlib import Path
import hashlib,json
root=Path(__file__).resolve().parents[1];d=root/'dist'
# Deterministic release marker from actual application code and data assets.
paths=sorted(p for p in d.rglob('*') if p.is_file() and p.name not in ('sw.js','offline-manifest.json') and not p.name.endswith('.partial'))
release=hashlib.sha256(''.join(hashlib.sha256(p.read_bytes()).hexdigest() for p in paths).encode()).hexdigest()[:16]
shell=['./','index.html','style.css','app.js','reader-controls.js','library.mjs','engine.mjs','assets.js','manifest.webmanifest','icon.svg','icon-192.png','icon-512.png','catalog.json','offline-manifest.json','texts/caesar--gall1.json']
sw=r'''// Generated by scripts/finalize.py; personal IndexedDB is never touched.
const SHELL='lectio-shell-RELEASE', DATA='lectio-assets-v1';
const FILES=FILES_JSON;
self.addEventListener('install',e=>e.waitUntil((async()=>{const c=await caches.open(SHELL);for(const path of FILES){const u=new URL(path,self.registration.scope);const r=await fetch(u,{cache:'reload'});if(!r.ok||r.redirected)throw Error('Shell unavailable: '+path);if(path.endsWith('.json')&&!r.headers.get('content-type')?.includes('json'))throw Error('Invalid shell data');await c.put(u,r);}await self.skipWaiting();})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{for(const k of await caches.keys())if(k.startsWith('lectio-shell-')&&k!==SHELL)await caches.delete(k);const data=await caches.open(DATA);for(const req of await data.keys())if(/\/(?:voice|kokoro|vendor)\/|\/(?:speech|voice-worker)\.js$/.test(new URL(req.url).pathname))await data.delete(req);await self.clients.claim();})()));
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method!=='GET'||u.origin!==self.location.origin||!u.href.startsWith(self.registration.scope))return;e.respondWith((async()=>{const shell=await caches.open(SHELL),data=await caches.open(DATA);if(e.request.mode==='navigate')return(await shell.match(new URL('index.html',self.registration.scope)))||fetch(e.request);const cached=await shell.match(e.request)||await data.match(e.request);if(cached)return cached;try{return await fetch(e.request);}catch{return new Response('This file is not saved offline. Reconnect to the local server or installation address and download it.',{status:503,headers:{'Content-Type':'text/plain'}});}})());});
'''.replace('RELEASE',release).replace('FILES_JSON',json.dumps(shell))
(d/'sw.js').write_text(sw)
paths=sorted(p for p in d.rglob('*') if p.is_file() and p.name!='offline-manifest.json' and not p.name.endswith('.partial'))
files=[{'path':str(p.relative_to(d)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in paths]
(d/'offline-manifest.json').write_text(json.dumps({'release':release,'files':files},separators=(',',':')))
print('Release',release,'files',len(files),'MB',round(sum(f['bytes'] for f in files)/1e6,1))
