import assert from 'node:assert/strict';
import fs from 'node:fs';
import {groupWorks,describe} from '../dist/library.mjs';
const c=JSON.parse(fs.readFileSync(new URL('../dist/catalog.json',import.meta.url)));
const groups=groupWorks(c), group=id=>groups.find(g=>g.books.some(b=>b.id===id));
assert.equal(groups.flatMap(g=>g.books).length,c.length);
assert.equal(new Set(groups.flatMap(g=>g.books.map(b=>b.id))).size,c.length);
assert.equal(group('vergil--aen1').title,'Aeneid');
assert.equal(group('vergil--aen1').books.length,13);
assert.deepEqual(group('vergil--aen1').books.filter(b=>!b.collection).map(b=>b.libraryOrder),Array.from({length:12},(_,i)=>i+1));
assert.equal(group('caesar--bc3').books.length,4);
assert.equal(group('cicero--verres.2.5').key,group('cicero--ver1').key);
assert.equal(group('cicero--tusc5').books.find(b=>b.id==='cicero--tusc5').libraryOrder,5);
assert.notEqual(group('erasmus--ep').key,group('erasmus--coll').key);
assert.equal(group('spinoza.ethica2').books.length,5);
assert.equal(group('prop4').books.filter(b=>!b.collection).length,4);
assert.equal(describe({id:'personal-1',era:'Personal',author:'Me',title:'My reading II'}).title,'My reading II');
const generic=[1,2].map(n=>({id:'x'+n,author:'Author',title:'Author',era:'Later'}));
assert.equal(groupWorks(generic).length,2);
console.log(`PASS: ${c.length} texts preserved across ${groups.length} groups; editions, numbering, personal titles and selection boundaries checked.`);
